#!/usr/bin/env node
"use strict";

/**
 * mobile/scripts/sync-web.js
 * Build the app's web payload: copy ../public into ./www and apply the
 * transforms that make a *bundled* copy of the client work.
 *
 * The web client is normally served by server.js, which does two things at
 * request time that simply do not happen when the same files are shipped inside
 * an APK and loaded from https://localhost:
 *
 *   1. injects `window.recaptchaEnabled` / `window.recaptchaSiteKey` and
 *      substitutes YOUR_SITE_KEY (see server.js "HTML templates" section);
 *   2. sets the Content-Security-Policy header (middleware/securityHeaders.js).
 *
 * It also serves /socket.io/socket.io.js, which inside the app has to come from
 * the real server rather than from the phone.
 *
 * Everything this script does is a transform of the real client — there is no
 * second copy of the game to keep in sync. Re-run it on every build.
 *
 * Usage:  API_BASE=https://play.example.com node scripts/sync-web.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.resolve(ROOT, "..", "public");
const OUT = path.join(ROOT, "www");

const API_BASE = (process.env.API_BASE || "").replace(/\/+$/, "");
if (!API_BASE) {
  console.error(
    "❌ API_BASE is required — the app has no same-origin server to fall back on.\n" +
      "   e.g. API_BASE=https://play.example.com npm run build"
  );
  process.exit(1);
}
try {
  // Fail loudly here rather than shipping a build that 404s every request.
  new URL(API_BASE);
} catch {
  console.error(`❌ API_BASE is not a valid URL: ${API_BASE}`);
  process.exit(1);
}

// Pages that must not ship inside a binary handed to players.
//   - admin tooling: obvious.
//   - subscription/tournaments: a subscription-mode product surface. A pot
//     deployment already redirects these away (server.js), and subscription.js
//     signs transactions through the extension-only `signTransaction`, which
//     Mobile Wallet Adapter does not implement — so bundling them would ship a
//     page that cannot work.
const EXCLUDE = new Set([
  "admin-tournaments.html",
  "admin-tournaments.js",
  "registration.html",
  "registration.js",
  "subscription.html",
  "subscription.js",
  "tournaments.html",
  "tournaments.js",
]);

// ── Copy ──────────────────────────────────────────────────────────────────────

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (EXCLUDE.has(entry.name)) continue;
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}

fs.rmSync(OUT, { recursive: true, force: true });
copyDir(SRC, OUT);

// ── Runtime config ────────────────────────────────────────────────────────────
// Read by public/net.js to point every relative /api call at the real server.

fs.writeFileSync(
  path.join(OUT, "app-config.js"),
  `// Generated by mobile/scripts/sync-web.js — do not edit.\n` +
    `window.__API_BASE__ = ${JSON.stringify(API_BASE)};\n` +
    `// reCAPTCHA cannot run at the https://localhost origin the APK is served\n` +
    `// from. The server accepts a verified Play Integrity attestation in its\n` +
    `// place for staked joins (see services/attestation.js).\n` +
    `window.recaptchaEnabled = false;\n` +
    `window.recaptchaSiteKey = "";\n`
);

// ── HTML transforms ───────────────────────────────────────────────────────────

const apiOrigin = new URL(API_BASE).origin;

// The bundled pages get no CSP header from the server, so the policy travels in
// a meta tag instead. Mirrors middleware/securityHeaders.js, minus the reCAPTCHA
// hosts (not used here) and plus the API origin, which is cross-origin now that
// the page itself is local.
const CSP = [
  "default-src 'self'",
  // The API origin is needed for the socket.io client, which the server serves
  // and which therefore cannot be a local path. Everything else is bundled.
  `script-src 'self' ${apiOrigin}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: https:",
  "font-src 'self' data:",
  `connect-src 'self' ${apiOrigin} wss: https:`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

function transformHtml(html) {
  // 1. socket.io's client is served BY the server, so it cannot be a local path.
  html = html.replace(
    /src="\/socket\.io\/socket\.io\.js"/g,
    `src="${API_BASE}/socket.io/socket.io.js"`
  );

  // 2. Drop reCAPTCHA script tags — they cannot function at this origin and
  //    would only log load errors on every page.
  html = html.replace(
    /\s*<script[^>]*recaptcha\/api\.js[^>]*>\s*<\/script>/g,
    ""
  );

  // 3. app-config.js must precede net.js, which reads window.__API_BASE__ at
  //    load time.
  html = html.replace(
    /(\s*)<script src="\/net\.js"><\/script>/,
    '$1<script src="/app-config.js"></script>$1<script src="/net.js"></script>'
  );

  // 4. CSP, since no header is applied to a file: / capacitor-served page.
  html = html.replace(
    /<head>/i,
    `<head>\n    <meta http-equiv="Content-Security-Policy" content="${CSP}">`
  );

  return html;
}

let htmlCount = 0;
for (const entry of fs.readdirSync(OUT, { withFileTypes: true })) {
  if (!entry.isFile() || !entry.name.endsWith(".html")) continue;
  const file = path.join(OUT, entry.name);
  fs.writeFileSync(file, transformHtml(fs.readFileSync(file, "utf8")));
  htmlCount++;
}

// A page that still references the server's site-key placeholder would ship a
// literal "YOUR_SITE_KEY" into the binary — catch it rather than guess.
for (const entry of fs.readdirSync(OUT)) {
  if (!entry.endsWith(".html")) continue;
  const body = fs.readFileSync(path.join(OUT, entry), "utf8");
  if (body.includes("YOUR_SITE_KEY")) {
    console.warn(`⚠️  ${entry} still contains YOUR_SITE_KEY after transform`);
  }
}

console.log(`✅ Synced ${htmlCount} pages to ${path.relative(ROOT, OUT)}`);
console.log(`   API base: ${API_BASE}`);
